package com.enhancebiz.service.common.dto;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface Column
{
	public String value();
	public boolean autoGenerated() default false;
	public boolean optimisticLock() default false;
	public boolean selectOnly() default false;
}
